name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Oracle VM and deploy Docker app
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            # Kill any process using port 3000
            sudo fuser -k 3000/tcp || true

            # Stop and remove existing container if it exists
            sudo docker stop node-test-container || true
            sudo docker rm node-test-container || true

            # Optionally remove old image
            sudo docker rmi my-node-app || true

            # Clone latest code
            rm -rf github-actions-docker-project || true
            git clone https://github.com/${{ github.repository }}.git
            cd github-actions-docker-project

            # Build and run new container
            sudo docker build -t my-node-app .
            sudo docker run -d -p 3000:3000 --name node-test-container my-node-app
          EOF
