name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Oracle VM and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            # Create a temp folder for deployment
            rm -rf github-actions-docker-project
            git clone https://github.com/${{ github.repository }}.git
            cd github-actions-docker-project

            # Stop old container if running
            docker stop node-test-container || true
            docker rm node-test-container || true

            # Build Docker image and run
            docker build -t my-node-app .
            docker run -d -p 3000:3000 --name node-test-container my-node-app
          EOF
